spring:
  application:
    name: '@project.name@'
  datasource:
    url: jdbc:postgresql://localhost:5432/demo-core-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ENC(JRd18pSSKFPnAqIZ8ds/t2/UnEQHahePzLYSjCyTe2FX6Cu1OyM0U/MDiqCWvKcr)
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update #create-drop #
    show-sql: true
    open-in-view: false

logging:
  config: src\main\resources\logback-spring.xml
  level:
    root: INFO #DEBUG #

jasypt:
  encryptor:
    password: secretKey